

## Problems with NumPy Broadcasting

In [7]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [12]:
import numpy as np

#Test

In [9]:
import os
os.getcwd()

'/content'

In [21]:
!git config --global user.email "pontus.soderhall@gmail.com"
!git config --global user.name "PontusSoederhaell"

In [24]:
!git add .
!git commit -m "colab commit"
!git push https://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@github.com/PontusSoederhaell/CMU_DeepLearning.git

[main 8d39de7] colab commit
 1 file changed, 1 insertion(+), 1 deletion(-)
 rewrite Recitations/0/0C_NumPy_Broadcasting_Pitfalls_(Part_4).ipynb (85%)
Enumerating objects: 34, done.
Counting objects: 100% (34/34), done.
Delta compression using up to 2 threads
Compressing objects: 100% (30/30), done.
Writing objects: 100% (30/30), 7.48 KiB | 106.00 KiB/s, done.
Total 30 (delta 11), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (11/11), completed with 1 local object.
remote: error: GH013: Repository rule violations found for refs/heads/main.
remote: 
remote: - GITHUB PUSH PROTECTION
remote:   —————————————————————————————————————————
remote:     Resolve the following violations before pushing again
remote: 
remote:     - Push cannot contain secrets
remote: 
remote:     
remote:      (?) Learn how to resolve a blocked push
remote:      https://docs.github.com/code-security/secret-scanning/working-with-secret-scanning-and-push-protection/working-with-push-protection-from-

### a. Element-wise multiplication


When working with 1D and 2D arrays in NumPy, a noteworthy challenge arises.

When you element-wise multiply a column vector with a shape of (a, 1) and a row vector with a shape of (1, a) in NumPy, the result is a 2D matrix with dimensions (a, a) and not a vector. This occurs due to NumPy's implicit broadcasting of both vectors to 2D matrices before performing element-wise multiplication.

The same broadcasting behavior occurs if the second input is a 1D array of shape (a,) instead of a row vector. NumPy treats 1D arrays as row vectors during operations, leading to the same outcome.

The only case where expected vector algebra behavior occurs is when both inputs are either column vectors or row vectors/1D arrays, as their shapes broadcast consistently.

It is very important to examine the shapes following elementwise multiplication when column vectors are involved.

In [ ]:
# Creating a 1D NumPy array from the list
numbers_list = [1, 2, 3, 4]
array_1 = np.array(numbers_list)
print("Array 1 is \n", array_1, " with dimensions ", array_1.shape)

# Creating another 1D NumPy array from the list
numbers_list = [5, 6, 7, 8]
array_2 = np.array(numbers_list)
print("Array 2 is \n", array_2, " with dimensions ", array_2.shape)

# Creating a 2D array with a column vector
column_vector = np.array([[1], [2], [3], [4]])
print("Column vector is \n", column_vector, " with dimensions ", column_vector.shape)

Array 1 is 
 [1 2 3 4]  with dimensions  (4,)
Array 2 is 
 [5 6 7 8]  with dimensions  (4,)
Column vector is 
 [[1]
 [2]
 [3]
 [4]]  with dimensions  (4, 1)


In [ ]:
# CASE 1: Performing Element-wise multiplication of two 1D arrays: Array_1 and Array_2
result_array_1 = array_1 * array_2
print("The result of element-wise multiplication is:", result_array_1," with dimensions ",result_array_1.shape)

The result of element-wise multiplication is: [ 5 12 21 32]  with dimensions  (4,)


In [ ]:
# CASE 2: Performing Element-wise multiplication of a column_vector and a 1D array(array_1)
result_array_2 = column_vector * array_1
print("The result of element-wise multiplication is:\n", result_array_2," with dimensions ",result_array_2.shape)

The result of element-wise multiplication is:
 [[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]  with dimensions  (4, 4)



When NumPy uses the @ operator to multiply two 1D arrays, it treats one of them as a row vector and the other as a column vector, resulting in a scalar value.

In [ ]:
# CASE 3: Performing Matrix multiplication of two 1D arrays: Array_1 and Array_2

result_array_3 = array_1 @ array_2
print("The result of matrix multiplication is:", result_array_3)

The result of matrix multiplication is: 70


### b. Element-wise Addition


Similar broadcasting behavior what we saw above is observed in the context of element-wise addition

In [ ]:
# CASE 4: Performing Element-wise Addition of two  1D arrays: Array_1 and Array_2

result_array_4 = array_1 + array_2
print("The result of element-wise Addition is:", result_array_4," with dimensions ",result_array_4.shape)

The result of element-wise Addition is: [ 6  8 10 12]  with dimensions  (4,)


In [ ]:
# CASE 5: Performing Element-wise Addition of a column_vector and a 1D array(array_1)

result_array_5 = column_vector + array_1
print("The result of element-wise Addition is:\n", result_array_5," with dimensions ",result_array_5.shape)

The result of element-wise Addition is:
 [[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]]  with dimensions  (4, 4)


### c. Swapping matrix multiplication (@) with element wise multiplication (*)


Consider a scenario where you want to perform a matrix multiplication. However, by mistake you use an asterisk * instead of a matrix multiplication operator (@). Despite the incorrect operator, the code will still run without error due to the broadcasting functionality in Python. The shapes matching might lead you to think that what you are doing is right whereas in reality, a matrix multiplication was required. You will get wrong values.

In [ ]:
# Create a 4x4 2D array with random values between 0 and 1
array_3 = np.random.rand(4, 4)
print("Randomly Generated 2D Array is :\n", array_3," with dimensions ", array_3.shape)

Randomly Generated 2D Array is :
 [[0.96596709 0.64017236 0.28261285 0.57271614]
 [0.85576492 0.2828296  0.05598984 0.54849124]
 [0.72233659 0.2010986  0.77504161 0.55601639]
 [0.80827201 0.75502135 0.9870186  0.85875641]]  with dimensions  (4, 4)


In [ ]:
# CASE 6: Matrix multiplication (@) involving a 1D array acting as a row vector and a 2D array
result_array_6 = array_1 @ array_3
print("The result of Matrix multiplication is:\n", result_array_6 ," with dimensions ",result_array_6.shape)

The result of Matrix multiplication is:
 [8.07759472 4.82921276 6.66779175 6.77277346]  with dimensions  (4,)


In [ ]:
# CASE 7: Substituting matrix multiplication (@) with element-wise multiplication (*) still functions due to Broadcasting

result_array_7 = array_1 * array_3
print("The result of element-wise multiplication is:\n", result_array_7 ," with dimensions ",result_array_7.shape)

The result of element-wise multiplication is:
 [[0.96596709 1.28034472 0.84783854 2.29086456]
 [0.85576492 0.5656592  0.16796952 2.19396498]
 [0.72233659 0.4021972  2.32512484 2.22406557]
 [0.80827201 1.5100427  2.96105579 3.43502566]]  with dimensions  (4, 4)


Similar observations can be made when using PyTorch instead of NumPy for matrix multiplication

In [ ]:
import torch

In [ ]:
#Create a 1D tensor

tensor1 = torch.tensor([1, 2, 3, 4])
print("Shape of tensor1:", tensor1.shape)

Shape of tensor1: torch.Size([4])


In [ ]:
#Create a random 2D tensor

tensor2 = torch.randint(0, 10, (4, 4))
print("Shape of tensor2:", tensor2.shape)

Shape of tensor2: torch.Size([4, 4])


In [ ]:
# CASE 8: Matrix multiplication (@) involving a 1D array acting as a row vector and a 2D array

matrix_product = tensor1 @ tensor2
print("Matrix multiplication result:\n", matrix_product, " with dimensions ",matrix_product.shape)

Matrix multiplication result:
 tensor([53, 16, 44, 43])  with dimensions  torch.Size([4])


In [ ]:
# CASE 9: Substituting matrix multiplication (@) with element-wise multiplication (*) still functions due to Broadcasting

elementwise_product = tensor1 * tensor2
print("Element-wise multiplication result:\n", elementwise_product, " with dimensions ",elementwise_product.shape)

Element-wise multiplication result:
 tensor([[ 7,  8, 15,  0],
        [ 9,  0,  3,  0],
        [ 8,  8, 21, 20],
        [ 1,  0, 12, 28]])  with dimensions  torch.Size([4, 4])
